apiVersion : apps/v1
kind: Deployment
metadata:
  name: spotify 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spotify
  template:
    metadata:
      labels:
        app: spotify 
    spec:
      containers:
        - name: spotify 
          image: labkino.azurecr.io/spotify
          ports:
          - containerPort: 8080